In [1]:
from deepface import DeepFace
#liveness
import tensorflow as tf

In [2]:
import cv2, numpy, datetime
import xlwings as xw
import numpy as np

In [3]:
import sys
print(sys.executable)


C:\Users\renji\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe


In [4]:
import os
import random
import mediapipe as mp

In [5]:
model = 'liveness.model'
model = tf.keras.models.load_model(model)

In [6]:
results = DeepFace.find(img_path='Renjith Anil.jpg', db_path = './ImagesAttendance',enforce_detection = False, model_name = 'VGG-Face')

24-11-07 01:48:43 - Searching Renjith Anil.jpg in 10 length datastore
24-11-07 01:48:47 - find function duration 4.00351357460022 seconds


In [7]:
results[0]['identity'][0]

'./ImagesAttendance\\Renjith Anil\\Renjith Anil.jpg'

In [8]:
results

[                                            identity  \
 0   ./ImagesAttendance\Renjith Anil\Renjith Anil.jpg   
 1  ./ImagesAttendance\Renjith Anil\Renjith Anil4.jpg   
 2  ./ImagesAttendance\Renjith Anil\Renjith Anil6.jpg   
 3  ./ImagesAttendance\Renjith Anil\Renjith Anil1.jpg   
 4  ./ImagesAttendance\Renjith Anil\Renjith Anil2.jpg   
 5  ./ImagesAttendance\Renjith Anil\Renjith Anil5.jpg   
 
                                        hash  target_x  target_y  target_w  \
 0  7c8ccbc0ae9af05fe49da4ad24bfd1bd471b244f         0         0       143   
 1  964f5e403a792adf272b5dfec532b4358fec4d30         0         0       863   
 2  c5c5875e209b86290b6395060b54d22e791d666d         0         0       863   
 3  83339303d2150b52479522db88cdb8ee053e4e0b         0         0       863   
 4  b63462bf488b1abb56142c90e2e0a4e6dbe3ef79         0         0       863   
 5  f98538a200f8c3b20d663b6396d95a63c68a39fa         0         0       863   
 
    target_h  source_x  source_y  source_w  source_

In [9]:
import os

# Example file path
file_path = results[0]['identity'][0]

# Extracting the name without the extension
file_name = os.path.splitext(os.path.basename(file_path))[0]

print(file_name)

Renjith Anil


In [10]:
import numpy as np

In [11]:
#xlwings
#initializing workbook and worksheet
workbook = xw.Book('attendance.xlsx')
sheet_name = datetime.date.today().isoformat()

try:
    worksheet = workbook.sheets(sheet_name)
except:
    worksheet = workbook.sheets.add(sheet_name)

In [12]:
#xlwings

worksheet.range('A1').value = 'STUDENT'
worksheet.range('B1').value = 'DATE'
worksheet.range('C1').value = 'TIME'

students=[]

In [13]:
def add_face(frame, name):
    # Save the new face image in the attendance folder
    path = f"./ImagesAttendance/{name}.jpg"
    cv2.imwrite(path, frame)
    print(f"Face added for {name}")
    return path

In [14]:
def save_cropped_face(frame, xmin, ymin, xmax, ymax, name):
    # Crop the face region
    face_crop = frame[ymin:ymax, xmin:xmax]
    
    # Save the cropped face image
    path = f"./ImagesAttendance/{name}.jpg"
    cv2.imwrite(path, face_crop)
    print(f"Face saved for {name}")
    return path

# Gesture Detection

In [15]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split

In [16]:
folder = './HandGesture/images'

In [17]:
gesture_labels = {
    'call_me': 0,
    'fingers_crossed': 1,
    'okay': 2,
    'paper': 3,
    'peace': 4,
    'rock': 5,
    'rock_on': 6,
    'scissor': 7,
    'thumbs': 8,
    'up': 9
}

In [18]:
!C:\Users\renji\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable


In [19]:
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(60, 60, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

In [20]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [21]:
def load_data(folder):
    images = []
    labels = []
    
    for gesture_dir in os.listdir(folder):
        label = gesture_labels.get(gesture_dir)
        if label is None:
            continue  
        path = os.path.join(folder, gesture_dir)
        for img_name in os.listdir(path):
            img_path = os.path.join(path, img_name)
            img = cv2.imread(img_path)
            img = cv2.resize(img, (60, 60))  
            images.append(img)
            labels.append(label)
    
    images = np.array(images)
    labels = np.array(labels)
    return images, labels

In [22]:
images, labels = load_data(folder)
x_train, x_val, y_train, y_val = train_test_split(images, labels, test_size=0.2, random_state=42)

In [23]:
train_gen = ImageDataGenerator(rescale=1.0/255.0)
val_gen = ImageDataGenerator(rescale=1.0/255.0)

In [24]:
model.fit(train_gen.flow(x_train, y_train, batch_size=32), validation_data=val_gen.flow(x_val, y_val, batch_size=32), epochs=10)

Epoch 1/10
132/132 [==============================] - 11s 70ms/step - loss: 1.0897 - accuracy: 0.6216 - val_loss: 0.3402 - val_accuracy: 0.8951
Epoch 2/10
132/132 [==============================] - 9s 68ms/step - loss: 0.2527 - accuracy: 0.9194 - val_loss: 0.3206 - val_accuracy: 0.8913
Epoch 3/10
132/132 [==============================] - 9s 66ms/step - loss: 0.1050 - accuracy: 0.9664 - val_loss: 0.1735 - val_accuracy: 0.9485
Epoch 4/10
132/132 [==============================] - 9s 67ms/step - loss: 0.0570 - accuracy: 0.9812 - val_loss: 0.1699 - val_accuracy: 0.9428
Epoch 5/10
132/132 [==============================] - 9s 66ms/step - loss: 0.0274 - accuracy: 0.9921 - val_loss: 0.1723 - val_accuracy: 0.9495
Epoch 6/10
132/132 [==============================] - 9s 66ms/step - loss: 0.0143 - accuracy: 0.9959 - val_loss: 0.0859 - val_accuracy: 0.9752
Epoch 7/10
132/132 [==============================] - 9s 67ms/step - loss: 0.0054 - accuracy: 0.9981 - val_loss: 0.0903 - val_accuracy: 0.976

# Functions for Gesture Detection


In [25]:
# Initialize gesture recognition model and MediaPipe
mp_hands = mp.solutions.hands
hands = mp_hands.Hands()
mp_drawing = mp.solutions.drawing_utils

In [26]:
# Show a random gesture for the user to match
def show_random():
    gesture_dir = random.choice(list(gesture_labels.keys()))
    gesture_path = os.path.join(folder, gesture_dir)
    random_image_path = os.path.join(gesture_path, random.choice(os.listdir(gesture_path)))
    img = cv2.imread(random_image_path)
    cv2.imshow('Gesture to Match', img)
    cv2.waitKey(3000)
    cv2.destroyWindow('Gesture to Match')
    gesture_label = gesture_labels[gesture_dir]
    return gesture_label

In [27]:
# Detect hand and draw landmarks
def detect(img):
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    result = hands.process(img_rgb)

    if result.multi_hand_landmarks:
        for hand in result.multi_hand_landmarks:
            mp_drawing.draw_landmarks(img, hand, mp_hands.HAND_CONNECTIONS)
    return img, result.multi_hand_landmarks


In [28]:
# Predict gesture
def predict(roi):
    if roi.size == 0:
        return None

    roi_resized = cv2.resize(roi, (60, 60))
    roi_resized = np.expand_dims(roi_resized, axis=0) / 255.0
    pred = model.predict(roi_resized)[0]

    ind = np.argsort(pred)[-5:][::-1]
    prob = pred[ind]
    labels = [(i, p) for i, p in zip(ind, prob)]
    return ind

In [29]:
def check(pred, true):
    if true in pred:
        print("Match found!")
        return True
    else:
        print("No match found. Try again.")
        return False

In [30]:
model2 = 'liveness.model'
model2 = tf.keras.models.load_model(model2)

In [33]:
# Initialize variables
cap = cv2.VideoCapture(0)
running = True
students = []
t0 = datetime.datetime.now().day  # Set t0 to the current day at the start
s = 2  # Row where the student details will be saved

while running:
    moment = datetime.datetime.now()
    hour = moment.hour
    minute = moment.minute
    day = moment.day
    month = moment.month
    year = moment.year
    date = f"{day}-{month}-{year}"
    time = f"{hour}:{minute}"

    # Check if the day has changed
    if day != t0:
        t0 = day
        worksheet = workbook.sheets.add(date)
        worksheet.range('A1').value = 'STUDENT'
        worksheet.range('B1').value = 'DATE'
        worksheet.range('C1').value = 'TIME'
        s = 2

    state, frame = cap.read()
    if not state:
        break

    # Perform face recognition
    res = DeepFace.find(frame, db_path='./ImagesAttendance/', enforce_detection=False, model_name='VGG-Face')

    if len(res[0]['identity']) > 0:
        name = res[0]['identity'][0].split('/')[2].split('\\')[0]
        xmin = int(res[0]['source_x'][0])
        ymin = int(res[0]['source_y'][0])
        w = res[0]['source_w'][0]
        h = res[0]['source_h'][0]
        xmax = int(xmin + w)
        ymax = int(ymin + h)

        img = frame[ymin:ymax, xmin:xmax]
        img = cv2.resize(img, (32, 32)).astype('float') / 255.0
        img = tf.keras.preprocessing.image.img_to_array(img)
        img = np.expand_dims(img, axis=0)
        liveness = model2.predict(img)
        liveness_value = liveness[0].argmax()

        # Draw bounding box and display name
        cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)
        cv2.putText(frame, name, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2)

        liveness_text = f"Liveness: {'Real' if liveness_value == 1 else 'Fake'}"
        cv2.putText(frame, liveness_text, (xmin, ymax + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2)

        if name in students:
            existing_date = worksheet.range(f'B{students.index(name) + 2}').value
            existing_time = worksheet.range(f'C{students.index(name) + 2}').value
            cv2.putText(frame, f"Logged in at {existing_time} on {existing_date}", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
        
        elif liveness_value == 1:
            cap.release()  # Release initial capture for gesture verification
            cv2.destroyAllWindows()

            # Start gesture recognition after closing the liveness window
            cap = cv2.VideoCapture(0)
            label = show_random()
            attempts = 0

            while attempts < 5:
                ret, gesture_frame = cap.read()
                processed_frame, hand = detect(gesture_frame)

                if hand:
                    h, w, _ = processed_frame.shape
                    x_min, y_min = w, h
                    x_max, y_max = 0, 0

                    for lm in hand[0].landmark:
                        x, y = int(lm.x * w), int(lm.y * h)
                        x_min, y_min = min(x, x_min), min(y, y_min)
                        x_max, y_max = max(x, x_max), max(y, y_max)

                    x_min, y_min = max(0, x_min - 20), max(0, y_min - 20)
                    x_max, y_max = min(w, x_max + 20), min(h, y_max + 20)

                    roi = processed_frame[y_min:y_max, x_min:x_max]
                    pred = predict(roi)

                    if check(pred, label):
                        cv2.putText(processed_frame, "Match!", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
                        print("Gesture matched!")
                        worksheet.range(f'A{s}').value, worksheet.range(f'B{s}').value, worksheet.range(f'C{s}').value = name, date, time
                        students.append(name)
                        s += 1
                        break
                    else:
                        cv2.putText(processed_frame, "Try again", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
                        attempts += 1
                else:
                    cv2.putText(processed_frame, "No hand detected", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

                cv2.imshow('Gesture Recognition', processed_frame)
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break

            cap.release()
            cv2.destroyAllWindows()

            # Reopen original video capture for liveness detection window
            cap = cv2.VideoCapture(0)
    else:
        cv2.putText(frame, "No face detected", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

    cv2.imshow('Attendance System', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

24-11-07 01:54:05 - Searching [[[ 73  69 105]
  [ 71  66 108]
  [ 69  64 116]
  ...
  [139 128 138]
  [134 125 133]
  [129 121 128]]

 [[ 71  67  99]
  [ 69  66 103]
  [ 67  63 109]
  ...
  [138 126 136]
  [135 123 132]
  [131 121 128]]

 [[ 70  66  91]
  [ 68  65  93]
  [ 65  63  99]
  ...
  [141 125 135]
  [140 125 134]
  [138 123 131]]

 ...

 [[188 181 164]
  [189 183 165]
  [190 184 165]
  ...
  [255 255 237]
  [255 255 237]
  [255 255 237]]

 [[187 179 162]
  [187 180 162]
  [188 181 161]
  ...
  [255 255 236]
  [255 255 236]
  [255 255 236]]

 [[182 174 157]
  [183 176 158]
  [184 177 157]
  ...
  [255 255 236]
  [255 255 236]
  [255 255 236]]] in 10 length datastore
24-11-07 01:54:06 - find function duration 0.7092711925506592 seconds
24-11-07 01:54:06 - Searching [[[ 65  64  74]
  [ 65  64  74]
  [ 63  63  74]
  ...
  [ 96  97  98]
  [ 93  96  97]
  [ 92  95  96]]

 [[ 64  63  73]
  [ 63  63  73]
  [ 63  63  74]
  ...
  [ 97  97  98]
  [ 94  96  97]
  [ 92  95  96]]

 [[ 62  6

In [ ]:
# # Initialize variables
# cap = cv2.VideoCapture(0)
# running = True
# students = []

# t0 = datetime.datetime.now().day  # Set t0 to the current day at the start
# s = 2  # Row where the student details will be saved

# while running:
#     moment = datetime.datetime.now()
#     hour = moment.hour
#     minute = moment.minute
#     day = moment.day
#     month = moment.month
#     year = moment.year

#     date = f"{day}-{month}-{year}"
#     time = f"{hour}:{minute}"

#     # Check if the day has changed
#     if day != t0:
#         t0 = day
#         worksheet = workbook.sheets.add(date)
#         worksheet.range('A1').value = 'STUDENT'
#         worksheet.range('B1').value = 'DATE'
#         worksheet.range('C1').value = 'TIME'
#         s = 2

#     state, frame = cap.read()
#     if not state:
#         break

#     # Perform face recognition
#     res = DeepFace.find(frame, db_path='./ImagesAttendance/', enforce_detection=False, model_name='VGG-Face')

#     if len(res[0]['identity']) > 0:
#         # Extracting the name without the extension
#         name = res[0]['identity'][0].split('/')[2].split('\\')[0]

#         # Get the face coordinates
#         xmin = int(res[0]['source_x'][0])
#         ymin = int(res[0]['source_y'][0])
#         w = res[0]['source_w'][0]
#         h = res[0]['source_h'][0]
#         xmax = int(xmin + w)
#         ymax = int(ymin + h)

#         # Liveness detection
#         img = frame[ymin:ymax, xmin:xmax]
#         img = cv2.resize(img, (32, 32))
#         img = img.astype('float') / 255.0
#         img = tf.keras.preprocessing.image.img_to_array(img)
#         img = np.expand_dims(img, axis=0)

#         liveness = model.predict(img)
#         liveness_value = liveness[0].argmax()  # 0 for fake, 1 for real

#         # Draw the bounding box and display name
#         cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)
#         cv2.rectangle(frame, (xmin, ymin - 25), (xmax, ymin), (255, 255, 255), -1)
#         cv2.putText(frame, name, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2, cv2.LINE_AA)

#         # Display liveness result
#         liveness_text = f"Liveness: {'Real' if liveness_value == 1 else 'Fake'}"
#         cv2.putText(frame, liveness_text, (xmin, ymax + 20), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 255, 255), 2, cv2.LINE_AA)

#         # Display date and time on the frame
#         cv2.putText(frame, f"Date: {date}", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2, cv2.LINE_AA)
#         cv2.putText(frame, f"Time: {time}", (20, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2, cv2.LINE_AA)

#         # Log attendance if liveness is real and name is not already logged
#         if liveness_value == 1 and name not in students:
#             worksheet.range(f'A{s}').value = name
#             worksheet.range(f'B{s}').value = date
#             worksheet.range(f'C{s}').value = time
#             students.append(name)
#             s += 1
#     else:
#         cv2.putText(frame, "No face detected", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2, cv2.LINE_AA)

#     # Show the frame with OpenCV
#     cv2.imshow('Attendance System', frame)

#     # Check for the exit condition (press 'q' to exit)
#     if cv2.waitKey(1) & 0xFF == ord('q'):
#         break

# cap.release()
# cv2.destroyAllWindows()


find function lasts  0.17710089683532715  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18119215965270996  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18382835388183594  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1781752109527588  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19152069091796875  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1807868480682373  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.17470622062683105  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17293667793273926  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16732168197631836  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17200922966003418  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16824603080749512  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1723928451538086  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repr

find function lasts  0.16996121406555176  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1796250343322754  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17474699020385742  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17446160316467285  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17377376556396484  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18857526779174805  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repr

find function lasts  0.17311859130859375  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18978190422058105  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17669296264648438  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1712329387664795  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1851499080657959  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1941361427307129  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repres

find function lasts  0.1855151653289795  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19018888473510742  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1726217269897461  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18089008331298828  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18118596076965332  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1854259967803955  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repres

find function lasts  0.1877758502960205  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18609356880187988  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18790841102600098  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17459630966186523  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1755664348602295  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17592763900756836  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.17335176467895508  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1771399974822998  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19302821159362793  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17916345596313477  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17888903617858887  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1912236213684082  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repre

find function lasts  0.18362069129943848  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17415356636047363  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17015290260314941  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17226552963256836  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17144274711608887  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17237639427185059  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

find function lasts  0.1890416145324707  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17636704444885254  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1748366355895996  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1762690544128418  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16993069648742676  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17308330535888672  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repres

find function lasts  0.17080903053283691  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17257928848266602  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17896246910095215  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17243075370788574  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17661452293395996  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16829657554626465  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

find function lasts  0.17146849632263184  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1701829433441162  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17254424095153809  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17324113845825195  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17296600341796875  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1731257438659668  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repre

find function lasts  0.18172240257263184  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19162607192993164  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1842198371887207  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1755068302154541  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17601537704467773  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17568540573120117  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repre

find function lasts  0.16909146308898926  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1737806797027588  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1951596736907959  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18832826614379883  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19605350494384766  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18262219429016113  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.17515897750854492  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18415093421936035  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17333459854125977  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17791509628295898  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17945504188537598  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1732480525970459  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repr

find function lasts  0.1730060577392578  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1729731559753418  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16950321197509766  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17963862419128418  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1754598617553711  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17012810707092285  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repres

find function lasts  0.18039870262145996  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17506814002990723  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17499971389770508  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18586969375610352  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18072009086608887  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18268108367919922  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

find function lasts  0.17222905158996582  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17467164993286133  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17354440689086914  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17711114883422852  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1708228588104248  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17425274848937988  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repr

find function lasts  0.17895102500915527  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17389392852783203  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17627239227294922  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17747998237609863  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17583250999450684  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17450475692749023  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

find function lasts  0.17472171783447266  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1910860538482666  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.178145170211792  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17537975311279297  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1914992332458496  seconds
1/1 [==============================] - 0s 16ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17912888526916504  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  represe

find function lasts  0.17116999626159668  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17439532279968262  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17215967178344727  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1721036434173584  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17647838592529297  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17711639404296875  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repr

1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16779184341430664  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1667470932006836  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16290903091430664  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17299985885620117  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1614670753479004  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.165

1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17081642150878906  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18112707138061523  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1757364273071289  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16485261917114258  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1835947036743164  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.162

find function lasts  0.17340683937072754  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1757371425628662  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17003655433654785  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18079328536987305  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18701577186584473  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1898956298828125  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.17435669898986816  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19319772720336914  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18603062629699707  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1743166446685791  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1904621124267578  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17410683631896973  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  repre

1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1859734058380127  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17909550666809082  seconds
1/1 [==============================] - 0s 16ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19028162956237793  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18911504745483398  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17154788970947266  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.15

find function lasts  0.16830205917358398  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17563390731811523  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1707305908203125  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17357921600341797  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1695849895477295  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17154932022094727  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

find function lasts  0.17199134826660156  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1702103614807129  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17053890228271484  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17228245735168457  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17046236991882324  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1721179485321045  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

find function lasts  0.1710033416748047  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16928672790527344  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17124152183532715  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1756134033203125  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16601824760437012  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16918134689331055  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.17874383926391602  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17263460159301758  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16839814186096191  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1723172664642334  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1685161590576172  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17078161239624023  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repre

find function lasts  0.1732921600341797  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1689739227294922  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1670536994934082  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17151641845703125  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1669938564300537  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1678605079650879  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  represen

find function lasts  0.17567706108093262  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1697406768798828  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16715526580810547  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17912960052490234  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17339324951171875  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.169020414352417  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repres

1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16958236694335938  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16174697875976562  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1626904010772705  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.15742921829223633  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17820167541503906  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16

find function lasts  0.17526984214782715  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18128228187561035  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18063807487487793  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17502093315124512  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17509913444519043  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17413544654846191  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

find function lasts  0.17966914176940918  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17743134498596191  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17987942695617676  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17364859580993652  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17257285118103027  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17227435111999512  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  rep

1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17113018035888672  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17345809936523438  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1765735149383545  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17219233512878418  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17179179191589355  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17

find function lasts  0.17582941055297852  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1799163818359375  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17461633682250977  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18709373474121094  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18150734901428223  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17866086959838867  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1767

1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17752599716186523  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18155694007873535  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17964792251586914  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1805276870727539  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18451857566833496  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18868064880371094  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18847370147705078  seconds
There are  9

find function lasts  0.17662358283996582  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1755199432373047  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1774578094482422  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19495391845703125  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17544150352478027  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17186999320983887  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17936

find function lasts  0.18401479721069336  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17614507675170898  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17398810386657715  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17562437057495117  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18033432960510254  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1756448745727539  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repr

find function lasts  0.1734151840209961  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17673850059509277  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1741030216217041  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18471598625183105  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17784643173217773  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17852449417114258  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1722395420074463  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function 

1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18161487579345703  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17932796478271484  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17836856842041016  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18049216270446777  seconds
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1796131134033203  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18483877182006836  seconds
1/1 [======================

1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1751391887664795  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17355132102966309  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18232011795043945  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17625904083251953  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17909455299377441  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17

find function lasts  0.18230700492858887  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1797802448272705  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18285632133483887  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1825103759765625  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17909550666809082  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18212294578552246  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

find function lasts  0.1744084358215332  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17563223838806152  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17369484901428223  seconds
1/1 [==============================] - 0s 12ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1742861270904541  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17456960678100586  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1756587028503418  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  repres

find function lasts  0.17903566360473633  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18117213249206543  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1721656322479248  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17449736595153809  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16946029663085938  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1729590892791748  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16747689247131348  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16448354721069336  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1673576831817627  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1702132225036621  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.16557908058166504  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.168

1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17818069458007812  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17859554290771484  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17591118812561035  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1802213191986084  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18013978004455566  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18

1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17823553085327148  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1775650978088379  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.17816710472106934  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1781611442565918  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18295764923095703  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.178

find function lasts  0.18138885498046875  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18428397178649902  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18514275550842285  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1840965747833252  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18661069869995117  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18378257751464844  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repr

find function lasts  0.18407964706420898  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18465089797973633  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18361759185791016  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1902627944946289  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1842799186706543  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18329215049743652  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

find function lasts  0.18501925468444824  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18286466598510742  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1830735206604004  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18802213668823242  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18662405014038086  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18635892868041992  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  repr

find function lasts  0.18538880348205566  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1843397617340088  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18799352645874023  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18326759338378906  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18192243576049805  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1871805191040039  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

find function lasts  0.18716883659362793  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1879291534423828  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18351459503173828  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18503165245056152  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18235516548156738  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18480491638183594  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repr

find function lasts  0.1870250701904297  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1865220069885254  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18695688247680664  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18448758125305176  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1862494945526123  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19168663024902344  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repres

find function lasts  0.18854427337646484  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18583369255065918  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18427395820617676  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18417954444885254  seconds
1/1 [==============================] - 0s 15ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.18796348571777344  seconds
1/1 [==============================] - 0s 13ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1851356029510498  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repr

find function lasts  0.19412684440612793  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1967165470123291  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19788026809692383  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.1928846836090088  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19351840019226074  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  representations_vgg_face.pkl
find function lasts  0.19916367530822754  seconds
1/1 [==============================] - 0s 14ms/step
There are  9  representations found in  repre

In [ ]:
import tensorflow as tf
print(tf.__version__)
